services:

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: movierec
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "5432:5432"
    command: 
      - "postgres"
      - "-c"
      - "statement_timeout=0"
      - "-c"
      - "idle_in_transaction_session_timeout=0"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d movierec"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - movie-network

  # Data Loader Service
  data-loader:
    build:
      context: .
      dockerfile: ./data/database/Dockerfile
    container_name: data_loader
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGUSER: admin
      PGPASSWORD: admin123
      PGDATABASE: movierec
    volumes:
      - ./data/raw/ml-25m:/app/data/raw/ml-25m:ro
    networks:
      - movie-network
    profiles: ["data-init"]

  # FastAPI Backend
  fastapi:
    build: ./src/api
    container_name: fastapi_service
    ports:
      - "8000:8000"
    environment:
      - TMDB_API_KEY=ce703cbcc8da689c5aa6a69369787ed9
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=movierec
    volumes:
      - "C:/docker-models:/app/models"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - movie-network

  # Streamlit Frontend
  streamlit:
    build: ./src/frontend
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://fastapi:8000/api/v1
      - TMDB_API_KEY=ce703cbcc8da689c5aa6a69369787ed9
      - DB_HOST=db
    depends_on:
      - fastapi
    networks:
      - movie-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - movie-network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - movie-network

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - movie-network

  # Kafka Consumer
  kafka-consumer:
    build: ./src/kafka_consumer
    container_name: kafka_consumer
    restart: on-failure
    environment:
      KAFKA_BROKER: kafka:29092
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: movierec
    depends_on:
      - kafka
      - db
    networks:
      - movie-network

  # Airflow Database
  airflow-db:
    image: postgres:15
    container_name: airflow_db_V2
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - movie-network

# Airflow Scheduler
  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow_scheduler_v2
    restart: on-failure
    command: scheduler
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    depends_on:
      airflow-db:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - "C:/docker-models:/app/models"
    networks:
      - movie-network

  # Airflow WebUI
  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow_webui_v2
    restart: on-failure
    command: webserver
    ports:
      - "8085:8080"
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    depends_on:
      airflow-db:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - movie-network

  # Airflow Init
  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow_init
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    command: >
      bash -c "
        airflow db init &&
        airflow users create
          --username admin
          --password admin
          --firstname Admin
          --lastname User
          --role Admin
          --email admin@cinematch.com
      "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - movie-network
    profiles: ["airflow-init"]

volumes:
  pgdata:
  airflow_pgdata:

networks:
  movie-network:
    driver: bridge